### ISSUE TITLE
FontBakery-OSX-v0.1.0 not working on macOS Big Sur 11.0.1?

### ISSUE THREAD

**Issue by eliheuer** [simoncozens/fontbakery-ui#10]
I used this app a few times on 10.15 Catalina and it worked, but after updating to macOS Big Sur 11.0.1(MacBook Air (Retina, 13-inch, 2020)) I just get a spinning beach ball and nothing happens.

Maybe I'm missing something or doing something wrong, just thought I'd leave a note in case someone else has the same issue and can confirm.

I was looking forward to using this more since I had tried to make an app like this in the past and couldn't figure out how to do it. Thanks!

**Comment by simoncozens** [comment]
I've confirmed on my virtual machine. Please try the latest artefact currently building at https://github.com/simoncozens/fontbakery-ui/actions/runs/368478621

**Comment by eliheuer** [comment]
Thanks! The version linked above worked on my 2020 MacBook Air running macOS 11.0.1.
