### ISSUE TITLE
[py2app] I can't run this on Linux

### ISSUE THREAD

**Issue by graphicore** [simoncozens/fontbakery-ui#3]
> py2app - Create standalone Mac OS X applications with Python

I don't know if we need something like such a standalone app on Linux, I just tried to follow the setup procedure in the README.

**Comment by graphicore** [comment]
Running:

```
$ python qfontbakery.py
```

Works for me:
 * starts the program
 * I can drop a font
 * progress bar works
 * result is rendered in an extra window.

The result window is not scaled well, this is probably due to my hi-res screen, I can however zoom in (pressing CTRL while scrolling with the mouse).

When I try to run another font via the same main window I get a crash:

```
QThread: Destroyed while thread is still running
Aborted (core dumped)
``` 

Also I get a couple of DeprecationWarnings:

```
qfontbakery.py:148: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.progress.setValue(value)
```

**Comment by simoncozens** [comment]
Yes, the py2app part is unnecessary on Linux. It may be best to deploy it just as a command line utility there. The fact that the thread is not destroyed after one report is a more important issue! Will fix.

**Comment by simoncozens** [comment]
I think this is fixed now, but please reopen if not.
