### ISSUE TITLE
Copy to pasteboard

### ISSUE THREAD

**Issue by davelab6** [simoncozens/fontbakery-ui#9]
Add a button to the report window "copy to pasteboard", with a tool tip that this will copy the markdown source of the report to the clip board suitable to post to github.

**Comment by simoncozens** [comment]
http://www.devx.com/opensource/Article/37233/0/page/3

**Comment by davelab6** [comment]
Link 404s

**Comment by simoncozens** [comment]
Huh, works for me. Anyway, it was just a note-to-self with OS X/Windows pasteboard code in it. I've implemented it in the above commit.

**Comment by davelab6** [comment]
🙏
